/* Generated by Together */

package com.javapatterns.prototype.concept2;

//和com.javapatterns.prototype.Client的调用有些不同
//为什么要这样调用呢?
//这里为什么参数要用具体类ConcretePrototype呢？
public class Client {
    public void operation(ConcretePrototype example) {
    }

    /**
     * @link aggregation 
     * @clientRole prototype
     * @clientCardinality 1
     * @supplierCardinality 1..*
     */
    private ConcretePrototype lnkConcretePrototype;
    private ConcretePrototype prototype;
}
